# Generated by Django 4.0.6 on 2022-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='long_text',
            field=models.TextField(blank=True),
        ),
    ]
